### PR TITLE
feat(pressure): Make pressure monitor message more brief

### LINKED ISSUE #423: Shorten Pressure Change Message
Shorten to the following to make it easier to find the numbers:

"EGBB QNH(QFE) now 1023(1012), was 1024(1013)"

https://github.com/VATSIM-UK/uk-controller-plugin/blob/31387f662d9f6d8a5de16fabbfabbf7bc7479ad7/src/plugin/metar/PressureChangeMessage.cpp#L24

### PR DESCRIPTION
**Pull request by AndyTWF**
This allows users to more quickly identify the important numbers.

Resolve #423

### CODE REVIEW

**Comment by AxonC** [comment]
@AndyTWF build failing :(

**Comment by AndyTWF** [comment]
Messed on main too... Trying to debug ctest :D

**Comment by AndyTWF** [comment]
@AxonC Should be fixed now... GH changed the actions runners and it broke the build!

**Review by AxonC — APPROVED** [review]

**Pull request merged**
