### PR TITLE
refactor(wake): Load wake from new dependency

### PR DESCRIPTION
**Pull request by AndyTWF**
Builds on #403 

- Refactor wake to use the WAKE_SCHEMES dependency, rather than the two individual dependencies.
- Also load extra wake metadata, for use in future features.

### CODE REVIEW

**Comment by AxonC** [comment]
@AndyTWF lmw when the built on changes are merged

**Comment by AndyTWF** [comment]
@AxonC All merged - think the files changed count is off, but still!

**Review by AxonC — APPROVED** [review]

**Pull request merged**
